### ISSUE TITLE
pod try fails

### ISSUE THREAD

**Issue by bulusoy** [KonradCLAPP/YawImageViewer#2]
pod try YawImageViewer
Updating spec repositories

Trying YawImageViewer
Performing CocoaPods Installation
Fetching podspec for `YawImageViewer` from `../`
[!] Unable to satisfy the following requirements:
- `YawImageViewer (from`../`)` required by `Podfile`
- `YawImageViewer (from`../`)` required by `Podfile`
- `YawImageViewer (= 0.1.0)` required by `Podfile.lock`

**Comment by KonradCLAPP** [comment]
I'm sorry that I've uploaded pod that didn't worked with pod try(actually i didn't now that such command exists :) ). Now it should be working, check it out!
